name: Testing
on: push

jobs:
  test_project:
  runs-on: ubuntu-latest
  steps:
  - users: actions/checkout@v2
  - name: Run Django unit tests
	run:
		pip3 install --user django
		cd airlines
		python3 manage.py test