name: Django CI

on:
  push:
    branches: [ main ]
    paths: -'airline/**'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit test
      run: |
        pip install django
        python manage.py test
        
